#############################################################################
# Makefile for building: precompile
# Generated by qmake (2.01a) (Qt 4.8.1) on: Fri Dec 13 14:39:02 2013
# Project:  precompile.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile precompile.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.1/mkspecs/macx-g++ -I. -Iinclude -Iinclude/xml
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS)    
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/xml/attribute.cpp \
		src/xml/commentnode.cpp \
		src/xml/elementnode.cpp \
		src/xml/pinode.cpp \
		src/xml/textnode.cpp \
		src/xml/xmlnode.cpp \
		src/ConfigElem.cpp \
		src/ConfigFile.cpp \
		src/Convert.cpp \
		src/ParseCmdLine.cpp \
		src/ParseElem.cpp \
		src/ParseQueue.cpp \
		src/Parser.cpp \
		src/ParserConf.cpp \
		src/precompile.cpp \
		src/PreParser.cpp \
		src/PrintArg.cpp \
		src/PrintConverter.cpp \
		src/Reserved.cpp \
		src/Var.cpp \
		src/Variables.cpp \
		src/ConvertElem.cpp \
		src/MatchElem.cpp \
		src/Matcher.cpp \
		src/Graph.cpp \
		src/ConvertConfig.cpp \
		src/ConstantsFinder.cpp \
		src/xml/XMLLexer.cpp \
		src/xml/XMLParser.cpp \
		src/lex.yy.cpp \
		src/gslapigenerator.cpp \
		src/gslparamgenerator.cpp 
OBJECTS       = obj/attribute.o \
		obj/commentnode.o \
		obj/elementnode.o \
		obj/pinode.o \
		obj/textnode.o \
		obj/xmlnode.o \
		obj/ConfigElem.o \
		obj/ConfigFile.o \
		obj/Convert.o \
		obj/ParseCmdLine.o \
		obj/ParseElem.o \
		obj/ParseQueue.o \
		obj/Parser.o \
		obj/ParserConf.o \
		obj/precompile.o \
		obj/PreParser.o \
		obj/PrintArg.o \
		obj/PrintConverter.o \
		obj/Reserved.o \
		obj/Var.o \
		obj/Variables.o \
		obj/ConvertElem.o \
		obj/MatchElem.o \
		obj/Matcher.o \
		obj/Graph.o \
		obj/ConvertConfig.o \
		obj/ConstantsFinder.o \
		obj/XMLLexer.o \
		obj/XMLParser.o \
		obj/lex.yy.o \
		obj/gslapigenerator.o \
		obj/gslparamgenerator.o
DIST          = /usr/local/Cellar/qt/4.8.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/warn_on.prf \
		precompile.pro
QMAKE_TARGET  = precompile
DESTDIR       = 
TARGET        = precompile

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: precompile.pro  /usr/local/Cellar/qt/4.8.1/mkspecs/macx-g++/qmake.conf /usr/local/Cellar/qt/4.8.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.1/mkspecs/features/warn_on.prf
	$(QMAKE) -o Makefile precompile.pro
/usr/local/Cellar/qt/4.8.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.1/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.1/mkspecs/common/g++-base.conf:
/usr/local/Cellar/qt/4.8.1/mkspecs/common/g++-macx.conf:
/usr/local/Cellar/qt/4.8.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.1/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.1/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.1/mkspecs/features/warn_on.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile precompile.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/precompile1.0.0 || $(MKDIR) obj/precompile1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/precompile1.0.0/ && (cd `dirname obj/precompile1.0.0` && $(TAR) precompile1.0.0.tar precompile1.0.0 && $(COMPRESS) precompile1.0.0.tar) && $(MOVE) `dirname obj/precompile1.0.0`/precompile1.0.0.tar.gz . && $(DEL_FILE) -r obj/precompile1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_clean: 

####### Compile

obj/attribute.o: src/xml/attribute.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/attribute.o src/xml/attribute.cpp

obj/commentnode.o: src/xml/commentnode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/commentnode.o src/xml/commentnode.cpp

obj/elementnode.o: src/xml/elementnode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/elementnode.o src/xml/elementnode.cpp

obj/pinode.o: src/xml/pinode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/pinode.o src/xml/pinode.cpp

obj/textnode.o: src/xml/textnode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/textnode.o src/xml/textnode.cpp

obj/xmlnode.o: src/xml/xmlnode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/xmlnode.o src/xml/xmlnode.cpp

obj/ConfigElem.o: src/ConfigElem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ConfigElem.o src/ConfigElem.cpp

obj/ConfigFile.o: src/ConfigFile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ConfigFile.o src/ConfigFile.cpp

obj/Convert.o: src/Convert.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Convert.o src/Convert.cpp

obj/ParseCmdLine.o: src/ParseCmdLine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ParseCmdLine.o src/ParseCmdLine.cpp

obj/ParseElem.o: src/ParseElem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ParseElem.o src/ParseElem.cpp

obj/ParseQueue.o: src/ParseQueue.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ParseQueue.o src/ParseQueue.cpp

obj/Parser.o: src/Parser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Parser.o src/Parser.cpp

obj/ParserConf.o: src/ParserConf.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ParserConf.o src/ParserConf.cpp

obj/precompile.o: src/precompile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/precompile.o src/precompile.cpp

obj/PreParser.o: src/PreParser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/PreParser.o src/PreParser.cpp

obj/PrintArg.o: src/PrintArg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/PrintArg.o src/PrintArg.cpp

obj/PrintConverter.o: src/PrintConverter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/PrintConverter.o src/PrintConverter.cpp

obj/Reserved.o: src/Reserved.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Reserved.o src/Reserved.cpp

obj/Var.o: src/Var.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Var.o src/Var.cpp

obj/Variables.o: src/Variables.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Variables.o src/Variables.cpp

obj/ConvertElem.o: src/ConvertElem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ConvertElem.o src/ConvertElem.cpp

obj/MatchElem.o: src/MatchElem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MatchElem.o src/MatchElem.cpp

obj/Matcher.o: src/Matcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Matcher.o src/Matcher.cpp

obj/Graph.o: src/Graph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Graph.o src/Graph.cpp

obj/ConvertConfig.o: src/ConvertConfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ConvertConfig.o src/ConvertConfig.cpp

obj/ConstantsFinder.o: src/ConstantsFinder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ConstantsFinder.o src/ConstantsFinder.cpp

obj/XMLLexer.o: src/xml/XMLLexer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/XMLLexer.o src/xml/XMLLexer.cpp

obj/XMLParser.o: src/xml/XMLParser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/XMLParser.o src/xml/XMLParser.cpp

obj/lex.yy.o: src/lex.yy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/lex.yy.o src/lex.yy.cpp

obj/gslapigenerator.o: src/gslapigenerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/gslapigenerator.o src/gslapigenerator.cpp

obj/gslparamgenerator.o: src/gslparamgenerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/gslparamgenerator.o src/gslparamgenerator.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

